# Generated by Django 4.0.3 on 2022-04-14 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_task_options_task_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='img',
        ),
    ]
