# Generated by Django 4.0.3 on 2022-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_task_options_remove_task_img_task_img1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('Description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'слайды',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='task',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='task',
            name='img3',
        ),
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
